services:
  db:
    env_file:
      - .env.test
    volumes: 
      - type: tmpfs
        target: /var/lib/postgresql/data

  django:
    env_file:
      - .env.test
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=DjangoBoilerplate.settings
    depends_on:
      fake-gcs-server:
        condition: service_started
    command: >
      sh -c "pip install -r requirements-dev.txt &&
             python manage.py migrate &&
             python -m pytest -v --tb=short --reuse-db --ds=DjangoBoilerplate.settings --cov=core --cov=api --cov=constants --cov=common --cov-report=term-missing --cov-config=.coveragerc $${COVERAGE_HTML:-}"

  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.49.0
    command: -scheme http -host 0.0.0.0 -port 9090
    volumes:
      - type: tmpfs
        target: /data

  prefect-server:
    env_file:
      - .env.test
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_UI_ENABLED: false
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres_prefect
    ports: []

  prefect-agent:
    env_file:
      - .env.test
    command: echo "Prefect agent disabled in test environment"
