services:
  db:
    env_file:
      - .env.test
    volumes: 
      - type: tmpfs
        target: /var/lib/postgresql/data

  django:
    env_file:
      - .env.test
    environment:
      - DEBUG=false
    command: >
      sh -c "python manage.py migrate &&
             pytest -v --tb=short --reuse-db"

  prefect-server:
    env_file:
      - .env.test
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_UI_ENABLED: false
    ports: []

  prefect-agent:
    env_file:
      - .env.test
    command: echo "Prefect agent disabled in test environment"
