services:
  db:
    env_file:
      - .env.test
    volumes: 
      - type: tmpfs
        target: /var/lib/postgresql/data

  django:
    env_file:
      - .env.test
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=DjangoBoilerplate.settings
    command: >
      sh -c "pip install -r requirements-dev.txt &&
             python manage.py migrate &&
             python -m pytest -v --tb=short --reuse-db --ds=DjangoBoilerplate.settings"

  prefect-server:
    env_file:
      - .env.test
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_UI_ENABLED: false
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres_prefect
    ports: []

  prefect-agent:
    env_file:
      - .env.test
    command: echo "Prefect agent disabled in test environment"
