services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  django:
    build: .
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - USE_POSTGRES=true
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      db:
        condition: service_healthy
      prefect-server:
        condition: service_started
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  prefect-server:
    image: prefecthq/prefect:3-latest
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}_prefect
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - prefect_data:/opt/prefect
    command: prefect server start --host 0.0.0.0

  prefect-agent:
    image: prefecthq/prefect:3-latest
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      - prefect-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    command: >
      sh -c "sleep 30 && 
             prefect work-pool create --type docker default-pool || true &&
             prefect worker start --pool default-pool"

volumes:
  postgres_data:
  prefect_data: