services:
  db:
    image: postgres:16-alpine
    environment:
      # Default values, can be overridden by env_file
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    env_file:
      - .env.dev
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} && psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c \"SELECT 1 FROM pg_database WHERE datname='$${POSTGRES_DB}_prefect'\" | grep -q 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  django:
    build: .
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - USE_POSTGRES=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - PREFECT_API_URL=http://prefect-server:4200/api
      # Google Cloud Storage configuration
      - USE_GCS_EMULATOR=${USE_GCS_EMULATOR}
      - GCS_EMULATOR_HOST=${GCS_EMULATOR_HOST}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      prefect-server:
        condition: service_healthy
      fake-gcs-server:
        condition: service_started
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_demo_data &&
             python manage.py runserver 0.0.0.0:8000"

  prefect-server:
    image: prefecthq/prefect:3-latest
    env_file:
      - .env.dev
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
      PREFECT_API_DATABASE_CONNECTION_URL: ${PREFECT_API_DATABASE_CONNECTION_URL}
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - prefect_data:/opt/prefect
    command: prefect server start --host 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')\""]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 120s

  prefect-agent:
    image: prefecthq/prefect:3-latest
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    env_file:
      - .env.dev
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    command: >
      sh -c "pip install prefect-docker &&
             sleep 60 && 
             prefect work-pool create --type docker default-pool || true &&
             prefect worker start --pool default-pool"

  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.49.0
    ports:
      - "9090:9090"
    command: -scheme http -host 0.0.0.0 -port 9090
    volumes:
      - gcs_data:/data

volumes:
  prefect_data:
  gcs_data:
