services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_test_db
    volumes: 
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoBoilerplate.settings
      - DJANGO_ENV=test
      - DEBUG=false
      - SECRET_KEY=django-insecure-test-2%l-xabc_5q%*ch4c+_s4z12)fopd!cl2(h$$6t(hj24glyd)nk
      - USE_POSTGRES=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=django_test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,django
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements-dev.txt &&
             export DJANGO_SETTINGS_MODULE=DjangoBoilerplate.settings &&
             python manage.py migrate &&
             pytest -v --tb=short --reuse-db"