services:
  db:
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data

  django:
    environment:
      - DEBUG=false
    command: >
      sh -c "python manage.py migrate &&
             python manage.py test --keepdb"

  prefect-server:
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_UI_ENABLED: false
    ports: []

  prefect-agent:
    command: echo "Prefect agent disabled in test environment"

volumes:
  postgres_test_data: