# Generated by Django 5.2.4 on 2025-08-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_experimental",
            field=models.BooleanField(
                default=False,
                help_text="Enable experimental features for this organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_experimental_user_override",
            field=models.BooleanField(
                default=False,
                help_text="Allow superuser to override experimental features (superuser only)",
            ),
        ),
    ]
