# Generated by Django 5.2.4 on 2025-08-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_models_align_with_spec'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_object',
        ),
        # Note: Index removals already done in migration 0011
        # Skipping duplicate RemoveIndex operations
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_organiz_9fed11_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_content_d03c4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_organiz_87ac03_idx',
        ),
        migrations.RenameIndex(
            model_name='evidencechunk',
            new_name='core_eviden_organiz_58c2ed_idx',
            old_name='core_evidencechunk_org_source_idx',
        ),
        migrations.RenameIndex(
            model_name='evidencefact',
            new_name='core_eviden_organiz_f46886_idx',
            old_name='core_evidencefact_org_source_idx',
        ),
        migrations.RenameIndex(
            model_name='evidenceinsight',
            new_name='core_eviden_organiz_dfa03e_idx',
            old_name='core_evidenceinsight_org_score_idx',
        ),
        migrations.RenameIndex(
            model_name='evidenceinsight',
            new_name='core_eviden_sentime_cf9922_idx',
            old_name='core_evidenceinsight_sentiment_idx',
        ),
        migrations.RenameIndex(
            model_name='evidencesource',
            new_name='core_eviden_organiz_3168d6_idx',
            old_name='core_evidencesource_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_organiz_e3e42d_idx',
            old_name='core_project_org_title_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='core_recomm_organiz_1f9b87_idx',
            old_name='core_recommendation_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='core_recomm_status_e131d2_idx',
            old_name='core_recommendation_status_idx',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='evidencefact',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Global repository tags', related_name='evidence_facts', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='evidenceinsight',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Global repository tags', related_name='evidence_insights', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='evidencesource',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Global repository tags', related_name='evidence_sources', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Global repository tags', related_name='projects', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Global repository tags', related_name='recommendations', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='tag',
            name='definition',
            field=models.TextField(blank=True, help_text='Optional description of the intended use or scope of the tag', verbose_name='Definition'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='The tag label', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidencesource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata including legacy tags', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(help_text='Organization this tag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddIndex(
            model_name='evidencefact',
            index=models.Index(fields=['created_at'], name='core_eviden_created_22d14e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesource',
            index=models.Index(fields=['created_at'], name='core_eviden_created_5c4d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='core_projec_start_d_1b55ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'title'], name='core_tag_organiz_0bb01e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'created_at'], name='core_tag_organiz_cbf48f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_tag_title_per_org'),
        ),
    ]
